name: test_env
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - alsa-lib=1.2.14=h5eee18b_0
  - asttokens=3.0.0=py313h06a4308_0
  - attr=2.5.1=h166bdaf_1
  - blas=1.0=openblas
  - brotli-python=1.0.9=py313h6a678d5_9
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.7.15=h06a4308_0
  - cairo=1.18.4=h3394656_0
  - comm=0.2.1=py313h06a4308_0
  - contourpy=1.3.1=py313hdb19cb5_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h1110e0f_3
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.8.11=py313h6a678d5_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.7.1=h6a678d5_0
  - fftw=3.3.10=nompi_hf1063bd_110
  - font-ttf-dejavu-sans-mono=2.37=hd3eb1b0_0
  - font-ttf-inconsolata=2.001=hcb22688_0
  - font-ttf-source-code-pro=2.030=hd3eb1b0_0
  - font-ttf-ubuntu=0.83=h8b1ccd4_0
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-anaconda=1=h8fa9717_0
  - fonts-conda-ecosystem=1=hd3eb1b0_0
  - fonttools=4.55.3=py313h5eee18b_0
  - freetype=2.13.3=ha770c72_1
  - gettext=0.25.1=h3f43e3d_1
  - gettext-tools=0.25.1=h3f43e3d_1
  - glib=2.84.0=h07242d1_0
  - glib-tools=2.84.0=h4833e2c_0
  - graphite2=1.3.14=h295c915_1
  - gst-plugins-base=1.24.7=h0a52356_0
  - gstreamer=1.24.7=hf3bb09a_0
  - harfbuzz=11.0.0=h76408a6_0
  - icu=75.1=he02047a_0
  - ipykernel=6.29.5=py313h06a4308_1
  - ipython=9.1.0=py313h06a4308_0
  - ipython_pygments_lexers=1.1.1=py313h06a4308_0
  - jedi=0.19.2=py313h06a4308_0
  - jupyter_client=8.6.3=py313h06a4308_0
  - jupyter_core=5.8.1=py313h06a4308_0
  - kiwisolver=1.4.8=py313h6a678d5_0
  - krb5=1.21.3=h723845a_4
  - lame=3.100=h7b6447c_0
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h6a678d5_0
  - libasprintf=0.25.1=h3f43e3d_1
  - libasprintf-devel=0.25.1=h3f43e3d_1
  - libcap=2.75=h39aace5_0
  - libclang-cpp20.1=20.1.8=default_hddf928d_0
  - libclang13=20.1.8=default_ha444ac7_0
  - libcups=2.3.3=hb8b1518_5
  - libdeflate=1.24=h86f0d12_0
  - libdrm=2.4.124=h5eee18b_0
  - libedit=3.1.20230828=h5eee18b_0
  - libegl=1.7.0=h5eee18b_2
  - libevent=2.1.12=hdbd6064_1
  - libexpat=2.7.1=hecca717_0
  - libffi=3.4.4=h6a678d5_1
  - libflac=1.4.3=h59595ed_0
  - libfreetype=2.13.3=ha770c72_1
  - libfreetype6=2.13.3=h48d6fc4_1
  - libgcc=15.1.0=h767d61c_4
  - libgcc-ng=15.1.0=h69a702a_4
  - libgcrypt-lib=1.11.1=hb9d3cd8_0
  - libgettextpo=0.25.1=h3f43e3d_1
  - libgettextpo-devel=0.25.1=h3f43e3d_1
  - libgfortran-ng=8.2.0=hdf63c60_1
  - libgfortran5=15.1.0=hcea5267_4
  - libgl=1.7.0=h5eee18b_2
  - libglib=2.84.0=h2ff4ddf_0
  - libglvnd=1.7.0=h5eee18b_2
  - libglx=1.7.0=h5eee18b_2
  - libgomp=15.1.0=h767d61c_4
  - libgpg-error=1.55=h3f2d84a_0
  - libiconv=1.18=h3b78370_2
  - libjpeg-turbo=3.1.1=hb25bd0a_0
  - libkrb5=1.21.3=h520c7b4_4
  - libllvm20=20.1.8=hecd9e04_0
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libmpdec=4.0.0=h5eee18b_0
  - libogg=1.3.5=h27cfd23_1
  - libopenblas=0.3.29=ha39b09d_0
  - libopus=1.3.1=h5eee18b_1
  - libpciaccess=0.18=h5eee18b_0
  - libpng=1.6.50=h421ea60_1
  - libpq=17.4=h02b6914_2
  - libsndfile=1.2.2=hc60ed4a_1
  - libsodium=1.0.18=h7b6447c_0
  - libsqlite=3.50.4=h0c1763c_0
  - libstdcxx=15.1.0=h8f9b012_4
  - libstdcxx-ng=15.1.0=h4852527_4
  - libsystemd0=257.7=h4e0b6ca_0
  - libtiff=4.7.0=h8261f1e_6
  - libuuid=2.38.1=h0b41bf4_0
  - libvorbis=1.3.7=h7b6447c_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h9b100fa_0
  - libxkbcommon=1.9.1=h69220b7_0
  - libxml2=2.13.8=h04c0eec_1
  - libzlib=1.3.1=hb9d3cd8_2
  - lmdb=0.9.31=hb25bd0a_0
  - lz4-c=1.10.0=h5888daf_1
  - matplotlib=3.10.0=py313h06a4308_1
  - matplotlib-base=3.10.0=py313h68cf311_1
  - matplotlib-inline=0.1.6=py313h06a4308_0
  - mpg123=1.32.9=hc50e24c_0
  - mysql-common=9.0.1=h266115a_6
  - mysql-libs=9.0.1=he0572af_6
  - ncurses=6.5=h7934f7d_0
  - nest-asyncio=1.6.0=py313h06a4308_0
  - nspr=4.37=h29cc59b_0
  - nss=3.115=hc3c8bcf_0
  - numpy-base=2.2.5=py313h7203c5b_1
  - openjpeg=2.5.3=h55fea9a_1
  - openldap=2.6.10=h8e75217_0
  - openssl=3.5.2=h26f9b46_0
  - packaging=25.0=py313h06a4308_0
  - parso=0.8.4=py313h06a4308_0
  - pcre2=10.44=hc749103_2
  - pexpect=4.9.0=py313h06a4308_0
  - pillow=11.3.0=py313h8db990d_0
  - pip=25.1=pyhc872135_2
  - pixman=0.46.4=h7934f7d_0
  - platformdirs=4.3.7=py313h06a4308_0
  - ply=3.11=py313h06a4308_1
  - prompt-toolkit=3.0.43=py313h06a4308_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - psutil=5.9.0=py313h5eee18b_1
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pulseaudio-client=17.0=hac146a9_1
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pygments=2.19.1=py313h06a4308_0
  - pyparsing=3.2.0=py313h06a4308_0
  - pyqt=5.15.10=py313h6a678d5_1
  - pyqt5-sip=12.13.0=py313h5eee18b_1
  - python=3.13.2=hf636f53_101_cp313
  - python-dateutil=2.9.0post0=py313h06a4308_2
  - python_abi=3.13=0_cp313
  - pyzmq=26.2.0=py313h6a678d5_0
  - qt-main=5.15.15=h993ce98_3
  - readline=8.3=hc2a1206_0
  - setuptools=72.1.0=py313h06a4308_0
  - sip=6.7.12=py313h6a678d5_1
  - six=1.17.0=py313h06a4308_0
  - sqlite=3.31.1=h7b6447c_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tk=8.6.13=noxft_hd72426e_102
  - tornado=6.5.1=py313h5eee18b_0
  - traitlets=5.14.3=py313h06a4308_0
  - tzdata=2025b=h04d1e81_0
  - wcwidth=0.2.13=py313h06a4308_0
  - wheel=0.45.1=py313h06a4308_0
  - xcb-util=0.4.1=h5eee18b_2
  - xcb-util-image=0.4.0=h5eee18b_2
  - xcb-util-keysyms=0.4.1=h5eee18b_0
  - xcb-util-renderutil=0.3.10=h5eee18b_0
  - xcb-util-wm=0.4.2=h5eee18b_0
  - xkeyboard-config=2.44=h5eee18b_0
  - xorg-libice=1.1.2=h9b100fa_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdamage=1.1.6=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxfixes=6.0.1=h9b100fa_0
  - xorg-libxrender=0.9.12=h9b100fa_0
  - xorg-libxxf86vm=1.1.6=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.8.1=hbcc6ac9_2
  - xz-gpl-tools=5.8.1=hbcc6ac9_2
  - xz-tools=5.8.1=hb9d3cd8_2
  - zeromq=4.3.5=h6a678d5_0
  - zlib=1.3.1=hb9d3cd8_2
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - llvmlite==0.44.0
      - numba==0.61.2
      - numpy==2.2.6
prefix: /home/frida/anaconda3/envs/test_env
